# Generated by Django 5.2.2 on 2025-06-08 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp1", "0002_post_like_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
