# Generated by Django 5.2.2 on 2025-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp1", "0006_remove_post_likes_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profile_photos"),
        ),
    ]
