# Generated by Django 5.2.2 on 2025-06-13 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp1", "0007_alter_profile_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "post")},
        ),
    ]
