# Generated by Django 5.2.2 on 2025-06-13 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp1", "0008_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
    ]
