# Generated by Django 5.2.2 on 2025-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twitterapp1", "0009_alter_like_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
